const String
EmptyClass = 'empty_class',
TotalClasses = 'total_classes',
GoogleSignin = 'google_signin',
BeltSelection = 'belt_selection',
Registry = 'registry',
AcceptAll = 'accept_all',
Logout = 'logout',
RegisterClass = 'register_class',
UnregisterClass = 'unregister_class',
Status = 'status',
Classes = 'classes',
LoginFailed = 'login_failed',
WhiteGrade = 'white_grade',
BlueGrade = 'blue_grade',
PurpleGrade = 'purple_grade',
BrownGrade = 'brown_grade',
BlackGrade = 'black_grade',
TodaysClasses = 'todays_classes',
NoClasses = 'no_classes',
Profile = 'profile',
SwipeToRemove = 'swipe_to_remove',
NameHint = "name_hint",
Teacher = "teacher"
;

final es = {
  EmptyClass: 'Clase vacía',
  TotalClasses: 'Clases atendidas',
  GoogleSignin: 'Acceso con Google',
  BeltSelection: 'Cuál es tu cinturón?',
  Registry: 'Registro',
  AcceptAll: 'Aceptar todos',
  Logout: 'Desconectar',
  RegisterClass: 'Apuntarse',
  UnregisterClass: 'Despuntarse',
  Status: 'Status',
  Classes: 'Clases',
  LoginFailed: 'No se pudo conectar. Inténtelo de nuevo porfavor.',
  WhiteGrade: 'Blanco',
  BlueGrade: 'Azúl',
  PurpleGrade: 'Morado',
  BrownGrade: 'Marron',
  BlackGrade: 'Negro',
  TodaysClasses: 'Clases de hoy',
  NoClasses: 'No hay clases hoy',
  Profile: 'Perfil',
  SwipeToRemove: 'Desliza hacia la izquierda para cancelar',
  NameHint: 'Intorduzca su nombre',
  Teacher: 'Profesores',
};

final en = {
  EmptyClass: 'Empty class',
  TotalClasses: 'Attended classes',
  GoogleSignin: 'Sign in with Google',
  BeltSelection: 'What\'s your belt?',
  Registry: 'Registry',
  AcceptAll: 'Accept all',
  Logout: 'Logout',
  RegisterClass: 'Register',
  UnregisterClass: 'Unregister',
  Status: 'Status',
  Classes: 'Classes',
  LoginFailed: 'Login Failed. Please try again',
  WhiteGrade: 'White',
  BlueGrade: 'Blue',
  PurpleGrade: 'Purple',
  BrownGrade: 'Brown',
  BlackGrade: 'Black',
  TodaysClasses: "Today's classes",
  NoClasses: 'There\'s no classes today',
  Profile: 'Profile',
  SwipeToRemove: 'Swipe left to remove user from class',
  NameHint: 'Enter your name',
  Teacher: 'Teachers',
};