final es = {
  'EmptyClass': 'Nadie en clase todavía',
  'TotalClasses': 'Clases atendidas',
  'GoogleSignin': 'Acceso con Google',
  'BeltSelection': 'Cuál es tu cinturón?',
  'Registry': 'Registro',
  'AcceptAll': 'Aceptar todos',
  'Logout': 'Desconectar',
  'RegisterClass': 'Apuntarse a clase',
  'UnregisterClass': 'Despuntarse de clase',
  'Status': 'Status',
  'Classes': 'Clases',
  'LoginFailed': 'No se pudo conectar. Inténtelo de nuevo porfavor.',
  'WhiteGrade': 'Blanco',
  'BlueGrade': 'Azúl',
  'PurpleGrade': 'Morado',
  'BrownGrade': 'Marron',
  'BlackGrade': 'Negro',
  'Today': 'Hoy',
  'NoClasses': 'No hay clases hoy',
  'Profile': 'Perfil',
  'SwipeToRemove': 'Desliza hacia la izquierda para cancelar',
  'NameHint': 'Intorduzca su nombre',
  'Teacher': 'Profesores',
  'AndOthers': 'y otros',
  'And': 'y',
  'By': 'Por',
  'You': 'Tú',
  'Full': 'lleno',
  'MatTime': 'Horas de Mat',
  'Hours': 'horas',
  'YouAttended': 'Has atendido',
  'ClassesThis': 'clases esta',
  'Week': 'semana',
  'Month': 'mes',
  'Year': 'año',
  'AttendedClasses': 'Clases atendidas',
  'Stats': 'Estadísticas',


  'NextBilling': 'El siguiente pago es el',
  'Unsubscribe': 'Darse de baja',
  'Subscribe': 'Suscribirse',
  'NotActiveSubscription': 'Tu subscripción no está activa todavia',
  'CreditCard': 'Tarjeta',
  'Account': 'Cuenta',
  'Membership': 'Afiliación',
  'CannotBeUndone': 'Esta operación no se puede deshacer',
  'KeepSubscription': 'Mantener subscripción',
  'AboutToPermanentlyDeleteSubscription':
      'Estás a punto de cancelar tu cuota de forma permanente',
  'Email': 'Email',
  'ChooseSubAndStartTraining': 'Escoje tu cuota y empieza a entrenar a tope',
  'Subscriptions': 'Cuotas',
  'GoToAccount': 'Volver a la Cuenta',
  'PaymentSuccessful': 'Pagado con Exito',
  'DisclaimerSubscription30Min': 'Tu subscripción puede tardar hasta 30 minutos en aparecer en tu cuenta',
};