// Mocks generated by Mockito 5.0.10 from annotations
// in checkin/test/blocs/gym_bloc_test.dart.
// Do not manually edit this file.

import 'package:checkin/src/repositories/gym_repository.dart' as _i2;
import 'package:checkin/src/util/date_util.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [GymRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGymRepository extends _i1.Mock implements _i2.GymRepository {
  MockGymRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DateUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateUtil extends _i1.Mock implements _i3.DateUtil {
  MockDateUtil() {
    _i1.throwOnMissingStub(this);
  }
}
