// Mocks generated by Mockito 5.0.10 from annotations
// in checkin/test/blocs/lessons_bloc_test.dart.
// Do not manually edit this file.

import 'package:checkin/src/repositories/lesson_repository.dart' as _i2;
import 'package:checkin/src/repositories/lesson_template_repository.dart' as _i3;
import 'package:checkin/src/repositories/user_repository.dart' as _i4;
import 'package:checkin/src/util/date_util.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [LessonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonRepository extends _i1.Mock implements _i2.LessonRepository {
  MockLessonRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [LessonTemplateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLessonTemplateRepository extends _i1.Mock implements _i3.LessonTemplateRepository {
  MockLessonTemplateRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DateUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateUtil extends _i1.Mock implements _i5.DateUtil {
  MockDateUtil() {
    _i1.throwOnMissingStub(this);
  }
}
